# Generated by Django 5.1.3 on 2024-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(default=0),
        ),
    ]
