# Generated by Django 5.1.3 on 2024-11-15 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_diseasetype_doctor_patient_publicservant_disease_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_deaths', models.IntegerField()),
                ('total_patients', models.IntegerField()),
                ('cname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.country')),
                ('disease_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.disease')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.publicservant')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'unique_together': {('email', 'cname', 'disease_code')},
            },
        ),
    ]
