from django.urls import path
from .views import *
urlpatterns = [
    path('', homeView, name='home_url'),
    path('sign_in', signInView, name='sign_in_url'),
    path('sign_out', signOutView, name='sign_out_url'),
    path('disease', diseaseView, name='disease_url'),
    path('personnel', personellView, name='personnel_url'),
    path('records', recordsView, name='records_url'),
    path('countries/', countryListView, name='country_list'),
    path('countries/create/', createCountryView, name='create_country'),
    path('countries/update/<str:cname>/', updateCountryView, name='update_country'),
    path('countries/delete/<str:cname>/', deleteCountryView, name='delete_country'),
    path('disease_type/', diseaseTypeListView, name='disease_type_list'),
    path('disease_type/create/', createDiseaseTypeView, name='create_disease_type'),
    path('disease_type/update/<int:id>/', updateDiseaseTypeView, name='update_disease_type'),
    path('disease_type/delete/<int:id>/', deleteDiseaseTypeView, name='delete_disease_type'),
    path('diseases/', diseaseListView, name='disease_list'),
    path('diseases/create/', createDiseaseView, name='create_disease'),
    path('diseases/update/<str:disease_code>/', updateDiseaseView, name='update_disease'),
    path('diseases/delete/<str:disease_code>/', deleteDiseaseView, name='delete_disease'),
    path('discover/', discoverListView, name='discover_list'),
    path('discover/create/', createDiscoverView, name='create_discover'),
    path('discover/update/<int:pk>/', updateDiscoverView, name='update_discover'),
    path('discover/delete/<int:pk>/', deleteDiscoverView, name='delete_discover'),
    path('patient_disease/', patientDiseaseListView, name='patient_disease_list'),
    path('patient_disease/create/', createPatientDiseaseView, name='create_patient_disease'),
    path('patient_disease/update/<int:pk>/', updatePatientDiseaseView, name='update_patient_disease'),
    path('patient_disease/delete/<int:pk>/', deletePatientDiseaseView, name='delete_patient_disease'),
    path('specialize/', specializeListView, name='specialize_list'),
    path('specialize/create/', specializeCreateView, name='specialize_create'),
    path('specialize/update/<int:pk>/', specializeUpdateView, name='specialize_update'),
    path('specialize/delete/<int:pk>/', specializeDeleteView, name='specialize_delete'),
    path('records_list/', recordListView, name='record_list'),
    path('records/create/', recordCreateView, name='record_create'),
    path('<int:pk>/update/', recordUpdateView, name='record_update'),
    path('<int:pk>/delete/', recordDeleteView, name='record_delete'),
]
